development: &development
  adapter: postgresql
  host: localhost
  database: detroit_dev
  encoding: unicode
  username: blake
  
test: &test
  adapter: postgresql
  host: localhost
  database: detroit_test
  encoding: unicode
  username: blake